import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">

      <body className="bg-black">
        <header className="bg-black text-white text-2xl flex flex-row justify-between p-10">
          <p>Транзакции</p>
          <div>
            <Link className="" href="/">Home</Link>
          </div>
        </header>
        <div>{children}</div>
        
        
      </body>
    </html>
  )
}
